DROP TABLE IF EXISTS detail;

CREATE TABLE detail (
  _index SERIAL NOT NULL PRIMARY KEY,
  address VARCHAR CONSTRAINT unq_address UNIQUE,
  price INT NOT NULL,
  body TEXT NOT NULL,
  subTitle VARCHAR NOT NULL,
  type VARCHAR NOT NULL,
  yearBuilt VARCHAR NOT NULL,
  heating VARCHAR NOT NULL,
  cooling VARCHAR NOT NULL,
  parking VARCHAR NOT NULL,
  lot INT NOT NULL,
  daysOnZillow VARCHAR NOT NULL,
  pricePerSqft INT NOT NULL,
  saves INT NOT NULL,
  bedRoom INT NOT NULL,
  bathRoom VARCHAR NOT NULL,
  heatingAndCooling VARCHAR NOT NULL,
  basement VARCHAR NOT NULL,
  flooring INT NOT NULL,
  otherInterior VARCHAR NOT NULL,
  size INT NOT NULL,
  amenities VARCHAR NOT NULL,
  spaces VARCHAR NOT NULL,
  typeAndStyle VARCHAR NOT NULL,
  builtIn VARCHAR NOT NULL,
  remodel VARCHAR NOT NULL,
  roof VARCHAR NOT NULL,
  exterior VARCHAR NOT NULL,
  otherConstruction VARCHAR NOT NULL,
  exteriorLot INT NOT NULL,
  lotWidth INT NOT NULL,
  otherExterior VARCHAR NOT NULL,
  parkingLong VARCHAR NOT NULL,
  soldDate VARCHAR NOT NULL,
  soldPrice INT NOT NULL,
  pastThirtydayView INT NOT NULL,
  savedLog INT NOT NULL
);