DROP TABLE IF EXISTS detailaddress;

CREATE TABLE detailaddress (
  id SERIAL NOT NULL,
  address VARCHAR NOT NULL PRIMARY KEY,
  price INT NOT NULL,
  body TEXT NOT NULL,
  subTitle VARCHAR NOT NULL,
  type VARCHAR NOT NULL,
  yearBuilt VARCHAR NOT NULL,
  heating VARCHAR NOT NULL,
  cooling VARCHAR NOT NULL,
  parking VARCHAR NOT NULL,
  lot SMALLINT NOT NULL,
  daysOnZillow VARCHAR NOT NULL,
  pricePerSqft SMALLINT NOT NULL,
  saves SMALLINT NOT NULL,
  bedRoom SMALLINT NOT NULL,
  bathRoom VARCHAR NOT NULL,
  heatingAndCooling VARCHAR NOT NULL,
  basement VARCHAR NOT NULL,
  flooring SMALLINT NOT NULL,
  otherInterior VARCHAR NOT NULL,
  size SMALLINT NOT NULL,
  amenities VARCHAR NOT NULL,
  spaces VARCHAR NOT NULL,
  typeAndStyle VARCHAR NOT NULL,
  builtIn VARCHAR NOT NULL,
  remodel VARCHAR NOT NULL,
  roof VARCHAR NOT NULL,
  exterior VARCHAR NOT NULL,
  otherConstruction VARCHAR NOT NULL,
  exteriorLot SMALLINT NOT NULL,
  lotWidth SMALLINT NOT NULL,
  otherExterior VARCHAR NOT NULL,
  parkingLong VARCHAR NOT NULL,
  soldDate VARCHAR NOT NULL,
  soldPrice INT NOT NULL,
  pastThirtydayView SMALLINT NOT NULL,
  savedLog SMALLINT NOT NULL
);